"""
Django settings for obstetric_care project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$z!&nw@++2f(-u)v7l$jcr%h768&bsnz+k@cd609fe-m7ybpyf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps de terceros
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'phonenumber_field',
    'django_filters',
    'rest_framework',
    'debug_toolbar',
    'django_extensions',
    'auditlog',


    # Apps de Obstetric Care (ORDEN IMPORTANTE)
    'inicioApp',
    'gestionApp',
    'matronaApp',
    'medicoApp',
    'tensApp',
    'legacyApp',
    'ingresoPartoApp',
    'recienNacidoApp', 
    'partosApp',
    'gestionProcesosApp',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Barra de debug (solo desarrollo)
]

ROOT_URLCONF = 'obstetric_care.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # ← AGREGADO
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # ← AGREGADO
                'django.template.context_processors.static',  # ← AGREGADO
            ],
        },
    },
]

WSGI_APPLICATION = 'obstetric_care.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import pymysql
pymysql.install_as_MySQLdb()

DATABASES = {
    # Base principal del sistema (es la que usa Django para migraciones nuevas)
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'obstetric_carebdd',
        'USER': 'root',
        'PASSWORD': '12345678',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
    },

    # Base histórica (solo lectura)
    'legacy': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'legacy_obstetric',
        'USER': 'root',
        'PASSWORD': '12345678',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4'},
    },
}

# Router para impedir migraciones y escrituras en la base legacy
DATABASE_ROUTERS = ['obstetric_care.dbrouters.LegacyRouter']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ═══════════════════════════════════════════════════════════════
# CONFIGURACIONES ADICIONALES NECESARIAS
# ═══════════════════════════════════════════════════════════════

# ──────────────────────────────────────────────────────────────
# AUTENTICACIÓN
# ──────────────────────────────────────────────────────────────
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/gestion/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'


# ──────────────────────────────────────────────────────────────
# CRISPY FORMS (Bootstrap 5)
# ──────────────────────────────────────────────────────────────
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# ──────────────────────────────────────────────────────────────
# PHONENUMBER FIELD (Números de teléfono chilenos)
# ──────────────────────────────────────────────────────────────
PHONENUMBER_DEFAULT_REGION = 'CL'
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'


# ──────────────────────────────────────────────────────────────
# DEBUG TOOLBAR (Solo en desarrollo)
# ──────────────────────────────────────────────────────────────
INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]


# ──────────────────────────────────────────────────────────────
# DJANGO REST FRAMEWORK (Configuración básica)
# ──────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}


# ──────────────────────────────────────────────────────────────
# AUDITLOG (Registro de auditoría)
# ──────────────────────────────────────────────────────────────
# Modelos que serán auditados automáticamente
# (Puedes agregar tus modelos aquí más adelante)


# ──────────────────────────────────────────────────────────────
# MENSAJES DE DJANGO (Bootstrap 5)
# ──────────────────────────────────────────────────────────────
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


# ──────────────────────────────────────────────────────────────
# SEGURIDAD (Solo para producción - comentado en desarrollo)
# ──────────────────────────────────────────────────────────────
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'


# ──────────────────────────────────────────────────────────────
# LOGGING (Registro de eventos)
# ──────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Crear directorio de logs si no existe
LOGS_DIR = BASE_DIR / 'logs'
if not LOGS_DIR.exists():
    LOGS_DIR.mkdir(parents=True, exist_ok=True)


# ═══════════════════════════════════════════════════════════════
# FIN DE CONFIGURACIONES
# ═══════════════════════════════════════════════════════════════
