# Generated by Django 5.2.8 on 2025-11-23 20:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingresoPartoApp', '0001_initial'),
        ('matronaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(help_text='Se genera automáticamente: PARTO-000001', max_length=20, unique=True, verbose_name='Número de Registro')),
                ('fecha_hora_admision', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuando ingresa para el parto', verbose_name='Fecha y Hora de Admisión')),
                ('fecha_hora_parto', models.DateTimeField(blank=True, help_text='Momento exacto del nacimiento', null=True, verbose_name='Fecha y Hora del Parto')),
                ('vih_tomado_prepartos', models.BooleanField(default=False, help_text='¿Se tomó VIH al ingresar a prepartos?', verbose_name='VIH tomado en Prepartos')),
                ('vih_tomado_sala', models.CharField(choices=[('NO', 'No'), ('SALA_1', 'Sala 1'), ('SALA_2', 'Sala 2'), ('SALA_3', 'Sala 3')], default='NO', help_text='Sala donde se tomó el VIH (si aplica)', max_length=20, verbose_name='VIH tomado en Sala')),
                ('edad_gestacional_semanas', models.IntegerField(help_text='Semanas completas al momento del parto', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(42)], verbose_name='Semanas de Embarazo')),
                ('edad_gestacional_dias', models.IntegerField(default=0, help_text='Ej: 38 semanas y 4 días', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Días adicionales')),
                ('monitor_ttc', models.BooleanField(default=False, help_text='¿Se usó monitor de contracciones?', verbose_name='Monitor TTC')),
                ('induccion', models.BooleanField(default=False, help_text='¿Se indujo el parto?', verbose_name='Inducción')),
                ('aceleracion_correccion', models.BooleanField(default=False, help_text='¿Se aceleró el trabajo de parto?', verbose_name='Aceleración o Corrección')),
                ('numero_tactos_vaginales', models.IntegerField(default=0, help_text='Número total de exámenes vaginales realizados', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Tactos Vaginales (TV)')),
                ('rotura_membrana', models.CharField(blank=True, choices=[('IOP', 'Inicio Espontáneo (IOP)'), ('RAM', 'Rotura Artificial de Membranas (RAM)'), ('REM', 'Rotura Espontánea de Membranas (REM)'), ('RPM', 'Rotura Prematura de Membranas (RPM)')], max_length=10, verbose_name='Rotura de Membrana')),
                ('tiempo_membranas_rotas', models.IntegerField(blank=True, help_text='Tiempo transcurrido con membranas rotas', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo Membranas Rotas (minutos)')),
                ('tiempo_dilatacion', models.IntegerField(blank=True, help_text='Duración de la fase de dilatación', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo Dilatación (minutos)')),
                ('tiempo_expulsivo', models.IntegerField(blank=True, help_text='Duración de la fase expulsiva', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo Expulsivo (minutos)')),
                ('libertad_movimiento', models.BooleanField(default=True, help_text='¿La paciente tuvo libertad de movimiento?', verbose_name='Libertad de Movimiento en Trabajo de Parto')),
                ('tipo_regimen', models.CharField(choices=[('CERO', 'Cero (ayuno absoluto)'), ('LIQUIDO', 'Líquido'), ('COMUN', 'Común'), ('OTRO', 'Otro')], default='LIQUIDO', max_length=10, verbose_name='Tipo de Régimen en Trabajo de Parto')),
                ('tipo_parto', models.CharField(choices=[('EUTOCICO', 'Eutócico (normal)'), ('DISTOCICO', 'Distócico (con complicaciones)'), ('CESAREA_URGENCIA', 'Cesárea de Urgencia'), ('CESAREA_ELECTIVA', 'Cesárea Electiva')], max_length=20, verbose_name='Tipo de Parto')),
                ('alumbramiento_dirigido', models.BooleanField(default=True, help_text='¿Se realizó alumbramiento dirigido?', verbose_name='Alumbramiento Dirigido')),
                ('clasificacion_robson', models.CharField(choices=[('Grupo 1', 'Grupo 1 - Nulíparas, único, cefálico, ≥37 sem, espontáneo'), ('Grupo 2.A', 'Grupo 2.A - Nulíparas, único, cefálico, ≥37 sem, inducción'), ('Grupo 2.B', 'Grupo 2.B - Nulíparas, único, cefálico, ≥37 sem, cesárea antes trabajo'), ('Grupo 3', 'Grupo 3 - Multíparas, único, cefálico, ≥37 sem, espontáneo'), ('Grupo 4', 'Grupo 4 - Multíparas, único, cefálico, ≥37 sem, inducción o cesárea'), ('Grupo 5.1', 'Grupo 5.1 - Multíparas, único, cefálico, ≥37 sem, cesárea previa, espontáneo'), ('Grupo 5.2', 'Grupo 5.2 - Multíparas, único, cefálico, ≥37 sem, cesárea previa, inducción'), ('Grupo 6', 'Grupo 6 - Nulíparas, único, podálica'), ('Grupo 7', 'Grupo 7 - Multíparas, único, podálica'), ('Grupo 8', 'Grupo 8 - Embarazos múltiples'), ('Grupo 9', 'Grupo 9 - Único, transversa u oblicua'), ('Grupo 10', 'Grupo 10 - Único, cefálico, ≤36 sem')], help_text='Clasificación de Robson para cesáreas', max_length=30, verbose_name='Clasificación de Robson')),
                ('posicion_materna_parto', models.CharField(choices=[('SEMISENTADA', 'Semisentada'), ('SENTADA', 'Sentada'), ('LITOTOMIA', 'Litotomía (acostada)'), ('D_DORSAL', 'Decúbito Dorsal'), ('D_LATERAL', 'Decúbito Lateral'), ('CUADRUPEDA', 'Cuadrúpeda'), ('CUCLILLAS', 'Cuclillas'), ('DE_PIE', 'De Pie'), ('OTRO', 'Otro')], max_length=20, verbose_name='Posición Materna en el Parto')),
                ('ofrecimiento_posiciones_alternativas', models.BooleanField(default=True, help_text='¿Se ofrecieron posiciones alternativas?', verbose_name='Ofrecimiento de Posiciones Alternativas del Parto')),
                ('estado_perine', models.CharField(choices=[('INDEMNE', 'Indemne (sin lesión)'), ('DESGARRO_G1', 'Desgarro Grado 1'), ('DESGARRO_G2', 'Desgarro Grado 2'), ('DESGARRO_G3_A', 'Desgarro Grado 3A'), ('DESGARRO_G3_B', 'Desgarro Grado 3B'), ('DESGARRO_G3_C', 'Desgarro Grado 3C'), ('DESGARRO_G4', 'Desgarro Grado 4'), ('FISURA', 'Fisura'), ('EPISIOTOMIA', 'Episiotomía')], max_length=20, verbose_name='Estado del Periné')),
                ('esterilizacion', models.BooleanField(default=False, help_text='¿Se realizó esterilización?', verbose_name='Esterilización')),
                ('revision', models.BooleanField(default=True, verbose_name='Revisión del Canal del Parto')),
                ('inercia_uterina', models.BooleanField(default=False, verbose_name='Inercia Uterina')),
                ('restos_placentarios', models.BooleanField(default=False, verbose_name='Restos Placentarios')),
                ('trauma', models.BooleanField(default=False, verbose_name='Trauma')),
                ('alteracion_coagulacion', models.BooleanField(default=False, verbose_name='Alteración de la Coagulación')),
                ('manejo_quirurgico_inercia', models.BooleanField(default=False, verbose_name='Manejo Quirúrgico de Inercia Uterina')),
                ('histerectomia_obstetrica', models.BooleanField(default=False, verbose_name='Histerectomía Obstétrica')),
                ('transfusion_sanguinea', models.BooleanField(default=False, verbose_name='Transfusión Sanguínea')),
                ('anestesia_neuroaxial', models.BooleanField(default=False, verbose_name='Anestesia Neuroaxial')),
                ('oxido_nitroso', models.BooleanField(default=False, verbose_name='Óxido Nitroso')),
                ('analgesia_endovenosa', models.BooleanField(default=False, verbose_name='Analgesia Endovenosa')),
                ('anestesia_general', models.BooleanField(default=False, verbose_name='Anestesia General')),
                ('anestesia_local', models.BooleanField(default=False, verbose_name='Anestesia Local')),
                ('analgesia_no_farmacologica', models.BooleanField(default=False, verbose_name='Analgesia NO Farmacológica')),
                ('balon_kinesico', models.BooleanField(default=False, verbose_name='Balón Kinésico')),
                ('lenteja_parto', models.BooleanField(default=False, verbose_name='Lenteja de Parto')),
                ('rebozo', models.BooleanField(default=False, verbose_name='Rebozo')),
                ('aromaterapia', models.BooleanField(default=False, verbose_name='Aromaterapia')),
                ('peridural_solicitada_paciente', models.BooleanField(default=False, verbose_name='Peridural Solicitada por Paciente')),
                ('peridural_indicada_medico', models.BooleanField(default=False, verbose_name='Peridural Indicada por Médico GO')),
                ('peridural_administrada', models.BooleanField(default=False, verbose_name='Peridural Administrada')),
                ('tiempo_espera_peridural', models.IntegerField(blank=True, help_text='Tiempo de espera para administración de peridural', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de espera entre indicación y administración (minutos)')),
                ('profesional_responsable', models.CharField(help_text='Profesional a cargo del parto', max_length=200, verbose_name='Profesional Responsable (Nombre - apellido)')),
                ('alumno', models.CharField(blank=True, help_text='Estudiante que participó en el parto', max_length=200, verbose_name='Alumno (Nombre - apellido)')),
                ('causa_cesarea', models.TextField(blank=True, help_text='Motivo por el cual se realizó cesárea', verbose_name='Causa de Cesárea')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales del parto', verbose_name='Observaciones')),
                ('uso_sala_saip', models.BooleanField(default=False, help_text='¿Se usó la sala SAIP (Sala de Atención Integral del Parto)?', verbose_name='USO DE SALA SAIP (SI/NO)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_parto', to='matronaApp.fichaobstetrica', verbose_name='Ficha Obstétrica')),
                ('ficha_ingreso', models.OneToOneField(blank=True, help_text='Vincula con la ficha de ingreso', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registro_parto', to='ingresoPartoApp.fichaparto', verbose_name='Ficha de Ingreso')),
            ],
            options={
                'verbose_name': 'Registro de Parto',
                'verbose_name_plural': 'Registros de Parto',
                'ordering': ['-fecha_hora_admision'],
                'indexes': [models.Index(fields=['numero_registro'], name='partosApp_r_numero__f4bca4_idx'), models.Index(fields=['ficha', '-fecha_hora_admision'], name='partosApp_r_ficha_i_51cd4e_idx'), models.Index(fields=['-fecha_hora_parto'], name='partosApp_r_fecha_h_6ada6e_idx')],
            },
        ),
    ]
