# Generated by Django 5.2.7 on 2025-10-28 20:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matronaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(help_text='Número único de registro de parto', max_length=20, unique=True, verbose_name='Número de Registro')),
                ('fecha_hora_admision', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que la paciente ingresa para el parto', verbose_name='Fecha y Hora de Admisión')),
                ('fecha_hora_parto', models.DateTimeField(blank=True, help_text='Momento exacto del nacimiento', null=True, verbose_name='Fecha y Hora del Parto')),
                ('vih_tomado_prepartos', models.BooleanField(default=False, help_text='¿Se tomó VIH al ingresar a prepartos?', verbose_name='VIH tomado en Prepartos')),
                ('vih_tomado_sala', models.CharField(choices=[('NO', 'No'), ('SALA_1', 'Sala 1'), ('SALA_2', 'Sala 2'), ('SALA_3', 'Sala 3')], default='NO', help_text='Sala donde se tomó el VIH (si aplica)', max_length=20, verbose_name='VIH tomado en Sala')),
                ('edad_gestacional_semanas', models.IntegerField(help_text='Semanas completas al momento del parto', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(42)], verbose_name='Edad Gestacional (semanas)')),
                ('edad_gestacional_dias', models.IntegerField(default=0, help_text='Días adicionales', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Edad Gestacional (días)')),
                ('monitor_ttc', models.BooleanField(default=False, help_text='¿Se utilizó monitor de contracciones?', verbose_name='Monitor TTC')),
                ('induccion', models.BooleanField(default=False, help_text='¿Se realizó inducción del parto?', verbose_name='Inducción')),
                ('aceleracion_correccion', models.BooleanField(default=False, help_text='¿Se aceleró o corrigió el trabajo de parto?', verbose_name='Aceleración o Corrección')),
                ('numero_tactos_vaginales', models.IntegerField(default=0, help_text='Cantidad total de tactos vaginales realizados', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Tactos Vaginales')),
                ('rotura_membrana', models.CharField(choices=[('ESPONTANEA', 'Espontánea'), ('ARTIFICIAL', 'Artificial'), ('MEMBRANAS_INTEGRAS', 'Membranas Íntegras')], help_text='Tipo de rotura de membranas', max_length=20, verbose_name='Rotura de Membrana')),
                ('tiempo_membranas_rotas', models.IntegerField(blank=True, help_text='Horas transcurridas desde la rotura de membranas', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo Membranas Rotas (horas)')),
                ('tiempo_dilatacion', models.IntegerField(blank=True, help_text='Duración del período de dilatación', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Dilatación (minutos)')),
                ('tiempo_expulsivo', models.IntegerField(blank=True, help_text='Duración del período expulsivo', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo Expulsivo (minutos)')),
                ('libertad_movimiento', models.BooleanField(default=False, help_text='¿Se permitió libertad de movimiento?', verbose_name='Libertad de Movimiento en Trabajo de Parto')),
                ('tipo_regimen', models.CharField(choices=[('CERO', 'Cero'), ('LIQUIDO', 'Líquido'), ('COMUN', 'Común'), ('OTRO', 'Otro')], help_text='Tipo de alimentación durante el trabajo de parto', max_length=30, verbose_name='Tipo de Régimen en Trabajo de Parto')),
                ('tipo_parto', models.CharField(choices=[('EUTOCICO', 'Eutócico'), ('DISTOCICO', 'Distócico'), ('CESAREA_URGENCIA', 'Cesárea de Urgencia'), ('CESAREA_ELECTIVA', 'Cesárea Electiva')], help_text='Clasificación del tipo de parto', max_length=30, verbose_name='Tipo de Parto')),
                ('alumbramiento_dirigido', models.BooleanField(default=False, help_text='¿Se realizó alumbramiento dirigido?', verbose_name='Alumbramiento Dirigido')),
                ('clasificacion_robson', models.CharField(choices=[('GRUPO_1', 'Grupo 1 - Nulíparas, único, cefálico, ≥37 sem, trabajo parto espontáneo'), ('GRUPO_2A', 'Grupo 2.A - Nulíparas, único, cefálico, ≥37 sem, inducido'), ('GRUPO_2B', 'Grupo 2.B - Nulíparas, único, cefálico, ≥37 sem, cesárea antes trabajo parto'), ('GRUPO_3', 'Grupo 3 - Multíparas sin cesárea previa, único, cefálico, ≥37 sem, espontáneo'), ('GRUPO_4', 'Grupo 4 - Multíparas sin cesárea previa, único, cefálico, ≥37 sem, inducido'), ('GRUPO_5_1', 'Grupo 5.1 - Multíparas con cesárea previa, único, cefálico, ≥37 sem, espontáneo'), ('GRUPO_5_2', 'Grupo 5.2 - Multíparas con cesárea previa, único, cefálico, ≥37 sem, inducido'), ('GRUPO_6', 'Grupo 6 - Nulíparas con feto único en presentación podálica'), ('GRUPO_7', 'Grupo 7 - Multíparas con feto único en presentación podálica'), ('GRUPO_8', 'Grupo 8 - Embarazos múltiples'), ('GRUPO_9', 'Grupo 9 - Presentaciones oblícuas o transversas'), ('GRUPO_10', 'Grupo 10 - Fetos únicos, cefálico, ≤36 semanas')], help_text='Clasificación de Robson para análisis de cesáreas', max_length=20, verbose_name='Clasificación de Robson')),
                ('posicion_materna_parto', models.CharField(choices=[('SEMISENTADA', 'Semisentada'), ('SENTADA', 'Sentada'), ('LITOTOMIA', 'Litotomía'), ('DORSAL', 'Decúbito Dorsal'), ('CUADRUPEDA', 'Cuadrúpeda'), ('LATERAL', 'Decúbito Lateral'), ('DE_PIE', 'De Pie'), ('CUCLILLAS', 'Cuclillas'), ('OTRO', 'Otro')], help_text='Posición adoptada por la madre durante el parto', max_length=30, verbose_name='Posición Materna en Parto')),
                ('ofrecimiento_posiciones_alternativas', models.BooleanField(default=False, help_text='¿Se ofrecieron posiciones alternativas para el parto?', verbose_name='Ofrecimiento de Posiciones Alternativas')),
                ('estado_perine', models.CharField(choices=[('INDEMNE', 'Indemne'), ('DESGARRO_G1', 'Desgarro Grado 1'), ('DESGARRO_G2', 'Desgarro Grado 2'), ('DESGARRO_G3A', 'Desgarro Grado 3A'), ('DESGARRO_G3B', 'Desgarro Grado 3B'), ('DESGARRO_G3C', 'Desgarro Grado 3C'), ('DESGARRO_G4', 'Desgarro Grado 4'), ('FISURA', 'Fisura'), ('EPISIOTOMIA', 'Episiotomía')], help_text='Condición del periné post-parto', max_length=30, verbose_name='Estado del Periné')),
                ('esterilizacion', models.BooleanField(default=False, help_text='¿Se realizó esterilización?', verbose_name='Esterilización')),
                ('revision', models.BooleanField(default=False, help_text='¿Se realizó revisión de cavidad uterina?', verbose_name='Revisión')),
                ('inercia_uterina', models.BooleanField(default=False, help_text='¿Presentó inercia uterina?', verbose_name='Inercia Uterina')),
                ('restos_placentarios', models.BooleanField(default=False, help_text='¿Se detectaron restos placentarios?', verbose_name='Restos Placentarios')),
                ('trauma', models.BooleanField(default=False, help_text='¿Hubo trauma durante el parto?', verbose_name='Trauma')),
                ('alteracion_coagulacion', models.BooleanField(default=False, help_text='¿Presentó alteración de la coagulación?', verbose_name='Alteración de la Coagulación')),
                ('manejo_quirurgico_inercia', models.BooleanField(default=False, help_text='¿Requirió manejo quirúrgico por inercia uterina?', verbose_name='Manejo Quirúrgico de Inercia Uterina')),
                ('histerectomia_obstetrica', models.BooleanField(default=False, help_text='¿Se realizó histerectomía obstétrica?', verbose_name='Histerectomía Obstétrica')),
                ('transfusion_sanguinea', models.BooleanField(default=False, help_text='¿Requirió transfusión sanguínea?', verbose_name='Transfusión Sanguínea')),
                ('anestesia_neuroaxial', models.BooleanField(default=False, help_text='¿Se administró anestesia neuroaxial?', verbose_name='Anestesia Neuroaxial')),
                ('oxido_nitroso', models.BooleanField(default=False, help_text='¿Se utilizó óxido nitroso?', verbose_name='Óxido Nitroso')),
                ('analgesia_endovenosa', models.BooleanField(default=False, help_text='¿Se administró analgesia endovenosa?', verbose_name='Analgesia Endovenosa')),
                ('anestesia_general', models.BooleanField(default=False, help_text='¿Se utilizó anestesia general?', verbose_name='Anestesia General')),
                ('anestesia_local', models.BooleanField(default=False, help_text='¿Se aplicó anestesia local?', verbose_name='Anestesia Local')),
                ('analgesia_no_farmacologica', models.BooleanField(default=False, help_text='¿Se utilizaron métodos de analgesia no farmacológica?', verbose_name='Analgesia NO Farmacológica')),
                ('balon_kinesico', models.BooleanField(default=False, help_text='¿Se utilizó balón kinésico?', verbose_name='Balón Kinésico')),
                ('lenteja_parto', models.BooleanField(default=False, help_text='¿Se utilizó lenteja de parto?', verbose_name='Lenteja de Parto')),
                ('rebozo', models.BooleanField(default=False, help_text='¿Se utilizó rebozo?', verbose_name='Rebozo')),
                ('aromaterapia', models.BooleanField(default=False, help_text='¿Se utilizó aromaterapia?', verbose_name='Aromaterapia')),
                ('peridural_solicitada_paciente', models.BooleanField(default=False, help_text='¿La paciente solicitó anestesia peridural?', verbose_name='Peridural Solicitada por Paciente')),
                ('peridural_indicada_medico', models.BooleanField(default=False, help_text='¿El médico gineco-obstetra indicó peridural?', verbose_name='Peridural Indicada por Médico GO')),
                ('peridural_administrada', models.BooleanField(default=False, help_text='¿Se administró la anestesia peridural?', verbose_name='Peridural Administrada')),
                ('tiempo_espera_peridural', models.IntegerField(blank=True, help_text='Tiempo entre indicación médica y administración de peridural', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Espera Peridural (minutos)')),
                ('profesional_responsable', models.CharField(help_text='Nombre completo del profesional responsable del parto', max_length=200, verbose_name='Profesional Responsable')),
                ('alumno', models.CharField(blank=True, help_text='Nombre del alumno que participó (si aplica)', max_length=200, verbose_name='Alumno')),
                ('causa_cesarea', models.TextField(blank=True, help_text='Indicación médica para cesárea', verbose_name='Causa de Cesárea')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones generales del parto', verbose_name='Observaciones')),
                ('uso_sala_saip', models.BooleanField(default=False, help_text='¿Se utilizó Sala de Atención Integral del Parto?', verbose_name='Uso de Sala SAIP')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Registro Activo')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_parto', to='matronaApp.fichaobstetrica', verbose_name='Ficha Obstétrica')),
            ],
            options={
                'verbose_name': 'Registro de Parto',
                'verbose_name_plural': 'Registros de Parto',
                'ordering': ['-fecha_hora_admision'],
            },
        ),
        migrations.CreateModel(
            name='DocumentosParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recuerdos_entregados', models.CharField(blank=True, help_text='Lista de recuerdos entregados según Ley Dominga', max_length=200, verbose_name='Recuerdos Entregados')),
                ('motivo_no_entrega_recuerdos', models.TextField(blank=True, help_text='Justificación si no se entregaron recuerdos', verbose_name='Motivo de No Entrega de Recuerdos')),
                ('retira_placenta', models.BooleanField(default=False, help_text='¿La familia retira la placenta?', verbose_name='Retira Placenta')),
                ('estampado_placenta', models.BooleanField(default=False, help_text='¿Se realizó estampado de placenta?', verbose_name='Estampado de Placenta')),
                ('folio_valido', models.CharField(blank=True, help_text='Número de folio válido del Registro Civil', max_length=50, verbose_name='Folio Válido')),
                ('folios_nulos', models.CharField(blank=True, help_text='Folios anulados (si aplica)', max_length=200, verbose_name='Folio/s Nulo/s')),
                ('manejo_dolor_no_farmacologico', models.TextField(blank=True, help_text='Descripción de métodos no farmacológicos utilizados', verbose_name='Manejo del Dolor No Farmacológico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('registro_parto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='partosApp.registroparto', verbose_name='Registro de Parto')),
            ],
            options={
                'verbose_name': 'Documentos de Parto',
                'verbose_name_plural': 'Documentos de Partos',
            },
        ),
        migrations.CreateModel(
            name='RegistroRecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('INDETERMINADO', 'Indeterminado')], help_text='Sexo del recién nacido', max_length=20, verbose_name='Sexo')),
                ('peso', models.IntegerField(help_text='Peso al nacer en gramos', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(8000)], verbose_name='Peso (gramos)')),
                ('talla', models.IntegerField(help_text='Longitud al nacer en centímetros', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(70)], verbose_name='Talla (cm)')),
                ('ligadura_tardia_cordon', models.BooleanField(default=False, help_text='¿Se realizó ligadura tardía del cordón umbilical?', verbose_name='Ligadura Tardía del Cordón (> 1 minuto)')),
                ('apgar_1_minuto', models.IntegerField(help_text='Puntaje Apgar al primer minuto', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Apgar al Minuto')),
                ('apgar_5_minutos', models.IntegerField(help_text='Puntaje Apgar a los cinco minutos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Apgar a los 5 Minutos')),
                ('tiempo_apego', models.IntegerField(blank=True, help_text='Tiempo de contacto piel con piel', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Apego (minutos)')),
                ('apego_canguro', models.BooleanField(default=False, help_text='¿Se realizó apego canguro?', verbose_name='Apego Canguro')),
                ('acompanamiento_preparto', models.BooleanField(default=False, help_text='¿Hubo acompañamiento en preparto?', verbose_name='Acompañamiento Preparto')),
                ('acompanamiento_parto', models.BooleanField(default=False, help_text='¿Hubo acompañamiento durante el parto?', verbose_name='Acompañamiento Parto')),
                ('acompanamiento_rn', models.BooleanField(default=False, help_text='¿Hubo acompañamiento con el recién nacido?', verbose_name='Acompañamiento RN')),
                ('motivo_parto_no_acompanado', models.CharField(choices=[('NA', 'No Aplica - Fue Acompañado'), ('NO_DESEA', 'No Desea'), ('NO_LLEGA', 'No Llega'), ('URGENCIA', 'Urgencia'), ('NO_TIENE', 'No Tiene Acompañante'), ('RURALIDAD', 'Ruralidad'), ('SIN_PASE', 'Sin Pase de Movilidad')], default='NA', help_text='Razón por la cual el parto no fue acompañado', max_length=50, verbose_name='Motivo Parto NO Acompañado')),
                ('persona_acompanante', models.CharField(choices=[('NADIE', 'Nadie'), ('PAREJA', 'Pareja'), ('MADRE', 'Madre'), ('HERMANA', 'Hermana'), ('AMIGA', 'Amiga'), ('OTRO', 'Otro')], default='NADIE', help_text='Quién acompañó a la madre', max_length=50, verbose_name='Persona Acompañante')),
                ('acompanante_secciona_cordon', models.BooleanField(default=False, help_text='¿El acompañante cortó el cordón umbilical?', verbose_name='Acompañante Secciona Cordón')),
                ('fecha_nacimiento', models.DateTimeField(help_text='Momento exacto del nacimiento', verbose_name='Fecha y Hora de Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('registro_parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='partosApp.registroparto', verbose_name='Registro de Parto')),
            ],
            options={
                'verbose_name': 'Registro de Recién Nacido',
                'verbose_name_plural': 'Registros de Recién Nacidos',
                'ordering': ['-fecha_nacimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='registroparto',
            index=models.Index(fields=['numero_registro'], name='partosApp_r_numero__f4bca4_idx'),
        ),
        migrations.AddIndex(
            model_name='registroparto',
            index=models.Index(fields=['ficha', '-fecha_hora_admision'], name='partosApp_r_ficha_i_51cd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='registroparto',
            index=models.Index(fields=['-fecha_hora_parto'], name='partosApp_r_fecha_h_6ada6e_idx'),
        ),
        migrations.AddIndex(
            model_name='registroreciennacido',
            index=models.Index(fields=['registro_parto', '-fecha_nacimiento'], name='partosApp_r_registr_bcaefa_idx'),
        ),
    ]
