# Generated by Django 5.2.7 on 2025-10-13 01:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionApp', '0001_initial'),
        ('matronaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde')], max_length=10, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.PositiveBigIntegerField(blank=True, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('frecuencia_respiratoria', models.PositiveBigIntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.PositiveBigIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_tens', to='matronaApp.fichaobstetrica')),
                ('tens_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_signos_vitales', to='gestionApp.tens')),
            ],
            options={
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Tratamiento_aplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('via_administracion', models.CharField(choices=[('VO', 'Oral (VO)'), ('IM', 'Intramuscular (IM)'), ('IV', 'Intravenosa (IV)'), ('TP', 'Tópica'), ('OT', 'Otras')], max_length=2)),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_aplicacion', models.TimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_tens', to='matronaApp.fichaobstetrica')),
                ('medicamento_ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matronaApp.medicamentoficha')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_aplicados', to='gestionApp.paciente')),
                ('tens', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_aplicados', to='gestionApp.tens')),
            ],
            options={
                'verbose_name': 'Tratamiento Aplicado',
                'verbose_name_plural': 'Tratamientos Aplicados',
            },
        ),
    ]
