# Generated by Django 5.2.7 on 2025-10-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la patología obstétrica', max_length=200, verbose_name='Nombre de la patología')),
                ('codigo_cie_10', models.CharField(choices=[('O10', 'O10 - Hipertensión preexistente'), ('O24', 'O24 - Diabetes mellitus en el embarazo'), ('O14', 'O14 - Preeclampsia'), ('O99.0', 'O99.0 - Anemia en el embarazo'), ('O99.2', 'O99.2 - Enfermedades endocrinas'), ('O26', 'O26 - Otras complicaciones del embarazo'), ('Otra', 'Otra patología obstétrica')], help_text='Clasificación Internacional de Enfermedades', max_length=100, verbose_name='Código CIE-10')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre la patología', null=True, verbose_name='Descripción')),
                ('nivel_de_riesgo', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], help_text='Nivel de riesgo para la gestante', max_length=20, verbose_name='Nivel de riesgo')),
                ('protocolo_seguimiento', models.TextField(blank=True, help_text='Indicaciones médicas para el seguimiento', null=True, verbose_name='Protocolo de seguimiento')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', help_text='Estado actual del registro', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patología',
                'verbose_name_plural': 'Patologías',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
