# Generated by Django 5.2.7 on 2025-10-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlesPrevios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_rut', models.CharField(max_length=12)),
                ('fecha_control', models.DateField()),
                ('semanas_gestacion', models.IntegerField(blank=True, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_uterina_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fcf_lpm', models.IntegerField(blank=True, null=True)),
                ('glucosa_mg_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('proteinuria', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'controles_previos',
                'ordering': ['-fecha_control'],
                'managed': False,
            },
        ),
    ]
