# Generated by Django 5.2.8 on 2025-11-23 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matronaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha_parto', models.CharField(help_text='Se genera automáticamente: FP-000001', max_length=20, unique=True, verbose_name='Número de Ficha de Parto')),
                ('tipo_paciente', models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('PREHOSPITALARIO', 'Prehospitalario'), ('FUERA_RED', 'Fuera de la Red Asistencial'), ('DOMICILIO_CON_PROF', 'Domicilio con Atención Profesional'), ('DOMICILIO_SIN_PROF', 'Domicilio sin Atención Profesional')], default='INSTITUCIONAL', help_text='Clasificación según origen', max_length=30, verbose_name='Tipo de Paciente')),
                ('origen_ingreso', models.CharField(choices=[('SALA', 'Sala'), ('UEGO', 'UEGO (Unidad Emergencia Gineco-Obstétrica)')], help_text='De dónde viene la paciente', max_length=20, verbose_name='Origen de Ingreso')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('hora_ingreso', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de Ingreso')),
                ('plan_de_parto', models.BooleanField(default=False, help_text='¿La paciente presentó plan de parto?', verbose_name='¿Tiene Plan de Parto?')),
                ('visita_guiada', models.BooleanField(default=False, help_text='¿Hizo visita previa a la unidad?', verbose_name='¿Realizó Visita Guiada?')),
                ('control_prenatal', models.BooleanField(default=True, help_text='¿Asistió a controles durante el embarazo?', verbose_name='¿Tuvo Control Prenatal?')),
                ('consultorio_origen', models.CharField(blank=True, help_text='Nombre del consultorio o CESFAM', max_length=200, verbose_name='Consultorio de Origen')),
                ('preeclampsia_severa', models.BooleanField(default=False, verbose_name='Preeclampsia Severa')),
                ('eclampsia', models.BooleanField(default=False, verbose_name='Eclampsia')),
                ('sepsis_infeccion_grave', models.BooleanField(default=False, verbose_name='Sepsis o Infección Sistémica Grave')),
                ('infeccion_ovular', models.BooleanField(default=False, verbose_name='Infección Ovular o Corioamnionitis')),
                ('otra_patologia', models.CharField(blank=True, help_text='Especificar otra patología si aplica', max_length=300, verbose_name='Otra Patología')),
                ('numero_aro', models.CharField(blank=True, help_text='Número de Alto Riesgo Obstétrico', max_length=20, verbose_name='Número ARO')),
                ('vih_tomado_prepartos', models.BooleanField(default=False, help_text='¿Se realizó test de VIH al ingresar a prepartos?', verbose_name='Se tomó VIH en Prepartos')),
                ('vih_tomado_sala', models.BooleanField(default=False, help_text='¿Se realizó test de VIH en sala de parto?', verbose_name='Se tomó VIH en Sala')),
                ('vih_orden_toma', models.CharField(blank=True, choices=[('1', 'Primera vez (1°)'), ('2', 'Segunda vez (2°)'), ('3', 'Tercera vez (3°)')], help_text='Número de vez que se toma el VIH', max_length=1, verbose_name='Orden de Toma (1°-2°-3°)')),
                ('sgb_pesquisa', models.BooleanField(default=False, help_text='¿Se realizó cultivo para SGB?', verbose_name='Pesquisa SGB Realizada')),
                ('sgb_resultado', models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=10, verbose_name='Resultado SGB')),
                ('antibiotico_sgb', models.BooleanField(default=False, help_text='¿Se administró antibiótico profiláctico por SGB positivo?', verbose_name='Antibiótico por SGB (NO POR RPM)')),
                ('vdrl_resultado', models.CharField(blank=True, choices=[('NO_REACTIVO', 'No Reactivo'), ('REACTIVO', 'Reactivo')], help_text='Resultado del test VDRL para sífilis', max_length=15, verbose_name='Resultado VDRL durante embarazo')),
                ('tratamiento_sifilis', models.BooleanField(default=False, help_text='¿Se administró tratamiento antibiótico para sífilis?', verbose_name='Tratamiento ATB por Sífilis al momento del Parto')),
                ('hepatitis_b_tomado', models.BooleanField(default=False, help_text='¿Se realizó serología para Hepatitis B?', verbose_name='Examen Hepatitis B - Tomado')),
                ('derivacion_gastro', models.BooleanField(default=False, help_text='¿Requiere derivación a especialista?', verbose_name='Derivación a Gastro-Hepatólogo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('activa', models.BooleanField(default=True, verbose_name='Ficha Activa')),
                ('ficha_obstetrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas_ingreso_parto', to='matronaApp.fichaobstetrica', verbose_name='Ficha Obstétrica')),
            ],
            options={
                'verbose_name': 'Ficha de Parto (Ingreso)',
                'verbose_name_plural': 'Fichas de Parto (Ingresos)',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['numero_ficha_parto'], name='ingresoPart_numero__40195a_idx'), models.Index(fields=['ficha_obstetrica', '-fecha_ingreso'], name='ingresoPart_ficha_o_a0a95f_idx')],
            },
        ),
    ]
