# Generated by Django 5.2.8 on 2025-11-23 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('INDETERMINADO', 'Indeterminado')], help_text='Sexo del recién nacido', max_length=20, verbose_name='Sexo')),
                ('peso', models.IntegerField(help_text='Peso al nacer en gramos', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(8000)], verbose_name='Peso (gramos)')),
                ('talla', models.IntegerField(help_text='Longitud al nacer en centímetros', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(70)], verbose_name='Talla (cm)')),
                ('ligadura_tardia_cordon', models.BooleanField(default=False, help_text='¿Se realizó ligadura tardía del cordón umbilical?', verbose_name='Ligadura Tardía del Cordón (> 1 minuto)')),
                ('apgar_1_minuto', models.IntegerField(help_text='Puntaje de Apgar al primer minuto de vida', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Apgar al Minuto')),
                ('apgar_5_minutos', models.IntegerField(help_text='Puntaje de Apgar a los 5 minutos de vida', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Apgar a los 5 Minutos')),
                ('fecha_nacimiento', models.DateTimeField(help_text='Momento exacto del nacimiento', verbose_name='Fecha y Hora de Nacimiento')),
                ('tiempo_apego', models.IntegerField(blank=True, help_text='Duración del apego piel con piel', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Apego (minutos)')),
                ('apego_canguro', models.BooleanField(default=False, help_text='¿Se realizó método canguro?', verbose_name='Apego Canguro')),
                ('acompanamiento_preparto', models.BooleanField(default=False, help_text='¿Hubo acompañante en preparto?', verbose_name='Acompañamiento en Preparto')),
                ('acompanamiento_parto', models.BooleanField(default=False, help_text='¿Hubo acompañante durante el parto?', verbose_name='Acompañamiento en Parto')),
                ('acompanamiento_rn', models.BooleanField(default=False, help_text='¿Hubo acompañante con el recién nacido?', verbose_name='Acompañamiento del RN')),
                ('motivo_no_acompanado', models.CharField(blank=True, choices=[('NO_DESEA', 'No desea'), ('NO_LLEGA', 'No llega acompañante'), ('URGENCIA', 'Urgencia'), ('NO_TIENE', 'No tiene acompañante'), ('RURALIDAD', 'Ruralidad'), ('SIN_PASE', 'Sin pase de movilidad')], help_text='Razón por la cual no hubo acompañamiento', max_length=20, verbose_name='Motivo Parto NO Acompañado')),
                ('persona_acompanante', models.CharField(blank=True, choices=[('PAREJA', 'Pareja'), ('MADRE', 'Madre'), ('HERMANA', 'Hermana'), ('AMIGA', 'Amiga'), ('OTRO', 'Otro'), ('NADIE', 'Nadie')], help_text='Quién acompañó a la paciente', max_length=10, verbose_name='Persona Acompañante')),
                ('acompanante_secciona_cordon', models.BooleanField(default=False, help_text='¿El acompañante cortó el cordón umbilical?', verbose_name='Acompañante Secciona Cordón')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('registro_parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='partosApp.registroparto', verbose_name='Registro de Parto')),
            ],
            options={
                'verbose_name': 'Registro de Recién Nacido',
                'verbose_name_plural': 'Registros de Recién Nacidos',
                'ordering': ['-fecha_nacimiento'],
            },
        ),
        migrations.CreateModel(
            name='DocumentosParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recuerdos_entregados', models.TextField(blank=True, help_text='Descripción de recuerdos entregados según Ley Dominga', verbose_name='Cuales Recuerdos (De no entregar justificar motivo)')),
                ('retira_placenta', models.BooleanField(default=False, help_text='¿La familia retira la placenta?', verbose_name='Retira Placenta')),
                ('estampado_placenta', models.BooleanField(default=False, help_text='¿Se realizó estampado de placenta?', verbose_name='Estampado de Placenta')),
                ('folio_valido', models.CharField(blank=True, help_text='Número de folio válido del Registro Civil', max_length=50, verbose_name='FOLIO VÁLIDO')),
                ('folios_nulos', models.CharField(blank=True, help_text='Folios anulados (si aplica)', max_length=200, verbose_name='FOLIO/S NULO/S')),
                ('manejo_dolor_no_farmacologico', models.TextField(blank=True, help_text='Descripción de métodos no farmacológicos utilizados', verbose_name='Manejo del Dolor No Farmacológico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Modificación')),
                ('registro_recien_nacido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='recienNacidoApp.registroreciennacido', verbose_name='Registro de Recién Nacido')),
            ],
            options={
                'verbose_name': 'Documentos de Parto',
                'verbose_name_plural': 'Documentos de Partos',
            },
        ),
        migrations.AddIndex(
            model_name='registroreciennacido',
            index=models.Index(fields=['registro_parto', '-fecha_nacimiento'], name='recienNacid_registr_11b649_idx'),
        ),
    ]
