# Generated by Django 5.2.7 on 2025-10-28 20:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import utilidad.rut_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(help_text='Ingrese RUT de la persona (formato: 12345678-9)', max_length=100, unique=True, validators=[utilidad.rut_validator._validar_rut], verbose_name='RUT')),
                ('Nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Apellido_Paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('Apellido_Materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('Fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Intersexual', 'Intersexual')], max_length=100, verbose_name='Sexo')),
                ('Inmigrante', models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=10, verbose_name='Inmigrante')),
                ('Nacionalidad', models.CharField(choices=[('Chile', 'Chile'), ('Argentina', 'Argentina'), ('Uruguay', 'Uruguay'), ('Colombia', 'Colombia'), ('Peru', 'Perú'), ('Venezuela', 'Venezuela'), ('Ecuador', 'Ecuador'), ('Brasil', 'Brasil'), ('Mexico', 'México'), ('Bolivia', 'Bolivia'), ('Paraguay', 'Paraguay')], default='Chile', max_length=100, verbose_name='Nacionalidad')),
                ('Pueblos_originarios', models.CharField(choices=[('No pertenece', 'No pertenece'), ('Mapuche', 'Mapuche'), ('Aymara', 'Aymara'), ('Quechua', 'Quechua'), ('Guaraní', 'Guaraní'), ('Rapa Nui', 'Rapa Nui'), ('Diaguita', 'Diaguita')], default='No pertenece', max_length=100, verbose_name='Pueblos originarios')),
                ('Discapacidad', models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=10, verbose_name='Discapacidad')),
                ('Tipo_de_Discapacidad', models.CharField(blank=True, help_text='Especificar solo si tiene discapacidad', max_length=200, null=True, verbose_name='Tipo de Discapacidad')),
                ('Privada_de_Libertad', models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=10, verbose_name='Privada de Libertad')),
                ('Trans_Masculino', models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=10, verbose_name='Trans Masculino')),
                ('Telefono', models.CharField(blank=True, max_length=100, verbose_name='Telefono')),
                ('Direccion', models.CharField(blank=True, max_length=100, verbose_name='Direccion')),
                ('Email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('Activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente', serialize=False, to='gestionApp.persona')),
                ('Estado_civil', models.CharField(choices=[('SOLTERA', 'Soltera'), ('CASADA', 'Casada'), ('CONVIVIENTE', 'Conviviente'), ('DIVORCIADA', 'Divorciada'), ('VIUDA', 'Viuda')], max_length=20, verbose_name='Estado Civil')),
                ('Previcion', models.CharField(choices=[('FONASA_A', 'FONASA A'), ('FONASA_B', 'FONASA B'), ('FONASA_C', 'FONASA C'), ('FONASA_D', 'FONASA D'), ('ISAPRE', 'Isapre'), ('PARTICULAR', 'Particular')], max_length=20, verbose_name='Previsión')),
                ('paridad', models.CharField(blank=True, help_text='Ejemplo: G3P2A0', max_length=50, verbose_name='Paridad')),
                ('Ductus_Venosus', models.CharField(choices=[('SIN_ESPECIFICAR', 'Sin Especificar'), ('DUCTUS_VENOSUS', 'Ductus Venosus'), ('DUCTUS_VENOSUS_SIN_CONTROL', 'Ductus Venosus Sin Control'), ('DUCTUS_VENOSUS_CONTROL', 'Ductus Venosus Con Control'), ('DUCTUS_VENOSUS_CONTROL_SIN_PREVENCION', 'Ductus Venosus Con Control Sin Prevención'), ('DUCTUS_VENOSUS_CONTROL_PREVENCION', 'Ductus Venosus Con Control Con Prevención'), ('DUCTUS_VENOSUS_CONTROL_PREVENCION_SIN_CONTROL', 'Ductus Venosus Con Control Con Prevención Sin Control')], default='SIN_ESPECIFICAR', max_length=70, verbose_name='Ductus Venosus')),
                ('control_prenatal', models.BooleanField(default=True, verbose_name='¿Tuvo Control Prenatal?')),
                ('Consultorio', models.CharField(choices=[('SIN_ESPECIFICAR', 'Sin Especificar'), ('CESFAM_ULTRAESTACION_DR_RAUL_SAN_MARTIN', 'CESFAM Ultraestación Dr. Raúl San Martín González (Chillán)'), ('CESFAM_LOS_VOLCANES', 'CESFAM Los Volcanes (Chillán)'), ('CESFAM_ISABEL_RIQUELME', 'CESFAM Isabel Riquelme (Chillán)'), ('CESFAM_QUINCHAMALI', 'CESFAM Quinchamalí (Chillán comuna)'), ('CESFAM_TERESA_BALDECHI', 'CESFAM Teresa Baldechi (San Carlos)'), ('CESFAM_DR_ALBERTO_GYHRA_SOTO', 'CESFAM Dr. Alberto Gyhra Soto (Quillón)'), ('CESFAM_MICHELL_CHANDIA_ALARCON', 'CESFAM Michell Chandia Alarcon (Coihueco)')], default='SIN_ESPECIFICAR', max_length=100, verbose_name='Consultorio de Origen')),
                ('IMC', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de Masa Corporal (10-60)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='IMC')),
                ('Preeclampsia_Severa', models.BooleanField(default=False, verbose_name='Preeclampsia Severa')),
                ('Eclampsia', models.BooleanField(default=False, verbose_name='Eclampsia')),
                ('Sepsis_o_Infeccion_SiST', models.BooleanField(default=False, verbose_name='Sepsis o Infección Sistémica Grave')),
                ('Infeccion_Ovular_o_Corioamnionitis', models.BooleanField(default=False, verbose_name='Infección Ovular o Corioamnionitis')),
                ('Acompañante', models.CharField(blank=True, max_length=120, verbose_name='Acompañante')),
                ('Contacto_emergencia', models.CharField(blank=True, max_length=30, verbose_name='Contacto de Emergencia')),
                ('Fecha_y_Hora_Ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(choices=[('Obstetricia General', 'Obstetricia General'), ('Ginecología', 'Ginecología'), ('Medicina Materno Fetal', 'Medicina Materno Fetal')], max_length=100)),
                ('Registro_medico', models.CharField(max_length=100, unique=True)),
                ('Años_experiencia', models.IntegerField()),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=100)),
                ('Activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.persona', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Matrona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(choices=[('Atención del Parto', 'Atención del Parto'), ('Control Prenatal', 'Control Prenatal'), ('Neonatología', 'Neonatología')], max_length=100)),
                ('Registro_medico', models.CharField(max_length=100, unique=True)),
                ('Años_experiencia', models.IntegerField()),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=100)),
                ('Activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.persona', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel', models.CharField(choices=[('Preparto', 'Preparto'), ('Parto', 'Parto'), ('Puerperio', 'Puerperio'), ('Neonatología', 'Neonatología')], max_length=100)),
                ('Años_experiencia', models.IntegerField()),
                ('Turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=100)),
                ('Certificaciones', models.CharField(choices=[('SVB', 'Soporte Vital Básico'), ('Parto Normal', 'Certificación en Parto Normal')], max_length=100)),
                ('Activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionApp.persona', verbose_name='Persona')),
            ],
        ),
    ]
